- name: Create a GCP Instance
  hosts: localhost
  vars:
    gcp_project: pulumi-367411
    gcp_cred_kind: serviceaccount
  tasks:
    - name: create a disk mapped from Debain image
      gcp_compute_disk:
        name: disk-instance
        size_gb: 10
        source_image: projects/debian-cloud/global/images/debian-11-bullseye-v20221102
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: disk
    - name: create a network
      google.cloud.gcp_compute_network:
        name: network-instance
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: network
    - name: create a address
      google.cloud.gcp_compute_address:
        name: address-instance
        region: us-central1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address
    - name: create the Ubuntu instance
      gcp_compute_instance:
        name: rhel8
        machine_type: e2-micro
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"